### ISSUE TITLE
dkms

### ISSUE THREAD

**Issue by mix931** [Engmostafa26/XEye-tp#1]
Too long or even infinity installation. How long it installing normal?![image](https://user-images.githubusercontent.com/99551414/154532549-48b9871c-615a-4791-a00f-58bf7f58800f.jpeg)

**Comment by Engmostafa26** [comment]
Hello Mix931

You just need to upgrade your kali, run "sudo apt upgrade -y" then it will work with no issues :)

**Comment by mix931** [comment]
It works! Thank you!!

**Comment by Engmostafa26** [comment]
Hi Mix931,

Please clone the tool again, now it is updated with more features and bugs fixed.  just clone the tool this time, then you don't need to clone the tool again, it will update itself automatically for each update in the future. Enjoy :)

**Comment by Engmostafa26** [comment]
The tool is updated and all issues are resolved.
