### ISSUE TITLE
dkms failure

### ISSUE THREAD

**Issue by giuseppepagnoni** [Engmostafa26/XEye-tp#2]
Hi, I'm running your tool on Kali 2022.2 on VMware.
I keep having dkms timeout even if I've upgraded all the packages. Sudo apt upgrade -y keeps saying I'm fully updated.
Thanks for helping.

G

![image](https://user-images.githubusercontent.com/48069163/169066730-84a93b73-fb45-4a5f-aa58-3c564ca5e4aa.png)

**Comment by Engmostafa26** [comment]
Hi, 

Sorry, I just noticed your comment now, it has been really too long till I responded, I really didn't notice.

Please clone the tool again as I modified some of the code to bypass that issue as it worked with people who had that issue, clone the tool again and try and let me know, you can message me directly through the XEye facebook page "https://www.facebook.com/XEye20212022" and I will help you :)

**Comment by Engmostafa26** [comment]
Hello @giuseppepagnoni 

Please clone the tool again, now the tool is updated with more features and almost all the bugs are fixed. just clone the tool this time and for each future update and the tool will update itself automatically.

**Comment by Engmostafa26** [comment]
The tool is updated and all issues are resolved.
