### ISSUE TITLE
Tries to reinstall custom driver although it's already installed

### ISSUE THREAD

**Issue by trueToastedCode** [Engmostafa26/XEye-tp#4]
I can either choose to install the custom driver or leave. However I've already installed a custom driver.

**Comment by Engmostafa26** [comment]
Hello, 

Can you share with me a screenshot of the issue?

Thanks,

**Comment by Engmostafa26** [comment]
Hello, 

The tool will be updated.

Many thanks,

**Comment by Engmostafa26** [comment]
Please run XEye-tp now and it will work, any install drive, the tool will skip. thanks.
