### ISSUE TITLE
XEye-tp couldn't be updated, please try again or reclone the tool

### ISSUE THREAD

**Issue by kosrosant** [Engmostafa26/XEye-tp#6]
Hello, after the python 3 command XEye-tp.py the following lines come out:

/usr/lib/python3/dist-packages/scapy/layers/ipsec.py:462: CryptographyDeprecationWarning: Blowfish has been deprecated
cipher=algorithms.Blowfish,
/usr/lib/python3/dist-packages/scapy/layers/ipsec.py:476: CryptographyDeprecationWarning: CAST5 has been deprecated
cipher=algorithms.CAST5,

[Info] --> Checking for updates, please wait .....

[Info] --> XEye-tp will be updated, please wait ......

[Warning] --> XEye-tp couldn't be updated, please try again or re clone the tool

What can be done in this situation?

**Comment by Engmostafa26** [comment]
Hello, at this moment you might need to reclone the tool, however, the tool might not work correctly as it is being updated to bypass more restrictions and we are adding more hacking features, the tool will be fully updated within the next few days.

**Comment by Gabrycraft20** [comment]
Same issue here, any news?

**Comment by Engmostafa26** [comment]
Hi, What is the language of your Linux?

**Comment by Gabrycraft20** [comment]
am actually on kali linux
and italian is the language

**Comment by Engmostafa26** [comment]
The tool only supports English-language Linux systems, however, you can run the "git pull" command in the XEye-tp directory and send me the output and we will configure the tool to read the lines in Italian.

**Comment by Gabrycraft20** [comment]
The output: Già aggiornato
that means already updated

**Comment by Engmostafa26** [comment]
Alright, Now XEye-tp will know whether or not it needs to be updated with the Italian language, please run the "git pull" command again and let me know the output.

**Comment by Gabrycraft20** [comment]
Here it is
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
Decompressione degli oggetti in corso: 100% (3/3), 747 byte | 149.00 KiB/s, fatto.
Da https://github.com/Engmostafa26/XEye-tp
   505462a..5fd8ef2  main       -> origin/main
Aggiornamento di 505462a..5fd8ef2
Fast-forward
 XEye-tp.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

**Comment by Gabrycraft20** [comment]
how should i proceed?

**Comment by Engmostafa26** [comment]
Hi, now you can run the tool and it will work after the update, please note that XEye-tp only supports English-based Linux systems, you might face more issues while it is running. it is more recommended to run Kali Linux in English as most of the tools only support English languages.
