### ISSUE TITLE
An issue running the code

### ISSUE THREAD

**Issue by saltshak** [Engmostafa26/XEye-tp#7]
Running the code on VMware Kali, unfortunately this is not working.
After running the program for a few times, this is what I get:

[Info] --> Checking for updates, please wait .....

[Info] --> A TP-Link USB WIFI adapter is detected 
-------------------------------------------------------------------------------------------------------

 [Permission] --> Would you like to proceed? [yes / no] yes

 [*][*][*] --> Updating your system, please wait ....  

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

 [*][*][*] --> Installing build-essentials, Please wait ....  

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

 [*][*][*] --> Installing bc, Won't take too long ....  

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

-------------------------------------------------------------------------------------------------------

 [*][*][*] --> Removing "r8188eu.ko module"  

 [*][*][*] --> Installing libelf-dev, Please wait ....  

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

-------------------------------------------------------------------------------------------------------

 [*][*][*] --> Installing dkms, please wait ..... 

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

 [*][*][*] --> Done installing dkms. proceeding further ....  

-------------------------------------------------------------------------------------------------------

 [*][*][*] --> Installing the required linux-headers 

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
linux-headers-6.1.0-kali5-amd64 is already the newest version (6.1.12-1kali2).
0 upgraded, 0 newly installed, 0 to remove and 1434 not upgraded.
-------------------------------------------------------------------------------------------------------

 [*][*][*] --> Git cloning the required drivers, Please wait ....... 

fatal: destination path 'rtl8188eus' already exists and is not an empty directory.
-------------------------------------------------------------------------------------------------------

 [*][*][*] --> Running Make command, Will take few minutes. Ignore the upcoming errors and warnings ......  

/home/kali/XEye-tp/rtl8188eus/os_dep/osdep_service.c: In function ‘rtw_change_ifname’:
/home/kali/XEye-tp/rtl8188eus/os_dep/osdep_service.c:2454:28: warning: passing argument 1 of ‘_rtw_memcpy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 2454 |         _rtw_memcpy(pnetdev->dev_addr, adapter_mac_addr(padapter), ETH_ALEN);
      |                     ~~~~~~~^~~~~~~~~~
/home/kali/XEye-tp/rtl8188eus/os_dep/osdep_service.c:899:24: note: expected ‘void *’ but argument is of type ‘const unsigned char *’
  899 | void _rtw_memcpy(void *dst, const void *src, u32 sz)
      |                  ~~~~~~^~~
/home/kali/XEye-tp/rtl8188eus/os_dep/osdep_service.c: In function ‘rtw_random32’:
/home/kali/XEye-tp/rtl8188eus/os_dep/osdep_service.c:2578:16: error: implicit declaration of function ‘prandom_u32’; did you mean ‘prandom_u32_max’? [-Werror=implicit-function-declaration]
 2578 |         return prandom_u32();
      |                ^~~~~~~~~~~
      |                prandom_u32_max
At top level:
cc1: note: unrecognized command-line option ‘-Wno-sometimes-uninitialized’ may have been intended to silence earlier diagnostics
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.1.0-kali5-common/scripts/Makefile.build:255: /home/kali/XEye-tp/rtl8188eus/os_dep/osdep_service.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.1.0-kali5-common/Makefile:2030: /home/kali/XEye-tp/rtl8188eus] Error 2
make: *** [Makefile:2065: modules] Error 2

 [*][*][*] --> Running "Make Install" command  

-------------------------------------------------------------------------------------------------------
install: cannot stat '8188eu.ko': No such file or directory
make: *** [Makefile:2071: install] Error 1

 [*] --> Running "modprobe 8188eu"  

modprobe: FATAL: Module 8188eu not found in directory /lib/modules/6.1.0-kali5-amd64
lo        no wireless extensions.

eth0      no wireless extensions.

-------------------------------------------------------------------------------------------------------

 [Warning] --> The WiFi adapter mode is not Auto or it is just missing, don't worry just follow the next instructions to bypass the restriction 

 [Info] --> It is normal to see such warnings from time to time as XEye-tp is trying to bypass the restrictions on your adapter. 
 [Instruction] --> UnPlug and plug in your WiFi USB adapter, WAIT FOR FEW SECONDS then run the tool again and XEye-tp will do the rest :)   

 [Assistance] --> If you need any further assistance, please contact us on our Facebook page: https://fb.com/xEyecs

**Comment by Engmostafa26** [comment]
Hi,


The tool is now updated and tested on different versions and it should work from your side. if you are still facing the same issue please let me know.
